#include "map.h"

static const TileID fantasyMap10x10_buffer[] =
{
TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_WALL,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_WALL,TILE_WALL,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_WALL,TILE_FLOOR,TILE_WALL,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_FLOOR,TILE_WALL,
TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL,TILE_FLOOR,TILE_FLOOR,TILE_WALL,TILE_WALL,TILE_WALL,TILE_WALL
};
static const map_t fantasyMap10x10 = {.size_tiles.width = 10, .size_tiles.height = 10, .tileSize_pixels = 16, .tileIds = fantasyMap10x10_buffer};

map_t maps[2] = {
    [FANTASY] = fantasyMap10x10
};